
services:
  php:
    build:
      context: ./docker/php
    container_name: challenge_php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - redis
    working_dir: /var/www/html
    environment:
      - APP_ENV=dev
    networks:
      - challenge

  web:
    image: nginx:alpine
    container_name: challenge_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - challenge

  mysql:
    image: mysql:8.0
    container_name: challenge_mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - challenge

  redis:
    image: redis:alpine
    container_name: challenge_redis
    networks:
      - challenge

volumes:
  mysql_data:

networks:
  challenge:
